/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as EmployeesRegisterRouteImport } from './routes/employees/register'
import { Route as EmployeesListRouteImport } from './routes/employees/list'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees/$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRegisterRoute = EmployeesRegisterRouteImport.update({
  id: '/employees/register',
  path: '/employees/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesListRoute = EmployeesListRouteImport.update({
  id: '/employees/list',
  path: '/employees/list',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/list': typeof EmployeesListRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/list': typeof EmployeesListRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/list': typeof EmployeesListRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees/$employeeId'
    | '/employees/list'
    | '/employees/register'
    | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees/$employeeId'
    | '/employees/list'
    | '/employees/register'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/employees/$employeeId'
    | '/employees/list'
    | '/employees/register'
    | '/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesListRoute: typeof EmployeesListRoute
  EmployeesRegisterRoute: typeof EmployeesRegisterRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/register': {
      id: '/employees/register'
      path: '/employees/register'
      fullPath: '/employees/register'
      preLoaderRoute: typeof EmployeesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/list': {
      id: '/employees/list'
      path: '/employees/list'
      fullPath: '/employees/list'
      preLoaderRoute: typeof EmployeesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesListRoute: EmployeesListRoute,
  EmployeesRegisterRoute: EmployeesRegisterRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
